
use baza;

INSERT INTO `user` (`id`, `username`, `auth_key`, `password_hash`, `password_reset_token`, `email`, `status`, `created_at`, `updated_at`, `verification_token`) VALUES
(1, 'admin123', 'CiBxu8TdlTC8CjGi-fvnnR0BaC3Hys9e', '$2y$13$pDM279Pou83rIp7fMS8nlOjEwt5iigizTzb/KtImuetOqycAN2ucC', NULL, 'admin@adm.si', 10, 1583961275, 1583961275, 'tlr7NMQSppd4Xqav9kc80XALeRGWYPX9_1583961275');


INSERT INTO `advert` (`id`, `naslov`, `povzetek`, `avtor`) VALUES
(1, 'Where does it come from?', 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise', 2),
(2, 'Second option', 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \"de Finibus Bonorum et Malorum\" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', 2),
(3, 'Wigi hej', 'Tale bo zadnji. Dolg bo natanko dva enostavna stavka.', 2),
(4, 'P naredmo še enga (4)', '-WIKI: https://jelix.org/en/ https://github.com/wsexport/tool https://tools.wmflabs.org/admin/tools  wikivir, knjige: https://sl.wikisource.org/wiki/Previsi http://nl.ijs.si/imp/wikivir/dl/WIKI00168-1876.html http://nl.ijs.si/ahlib/ http://lit.ijs.si/leposl.html  SAMP Kristop Junge: https://www.kristophjunge.com/saml-identity-provider-docker-container', 2),
(5, 'Peti po vrsti', 'The first recorded use of the term was in 1499 by Johannes Trithemius in his Steganographia, a treatise on cryptography and steganography, disguised as a book on magic. Generally, the hidden messages appear to be (or to be part of) something else: images, articles, shopping lists, or some other cover text. For example, the hidden message may be in invisible ink between the visible lines of a private letter. Some implementations of steganography that lack a shared secret are forms of security through obscurity, and key-dependent steganographic schemes adhere to Kerckhoffs\'s principle', 1),
(6, 'Sixth and last', 'Magic numbers used by programmers: In TIFF (Tagged Image File Format), the second 16-bit word of every file is 42, \"an arbitrary but carefully chosen number that further identifies the file as a TIFF file\". In the reiser4 file system, 42 is the inode number of the root directory. In the military IRIG 106 Chapter 10 data recording standard, the hex value 0x464F52545974776F (ASCII \"FORTYtwo\") is used as a magic number to identify directory blocks. The GNU C Library, a set of standard routines available for use in computer programming, contains a function—memfrob()—which performs an XOR combinati', 1);
